describe("api.utils", function()
    local api_utils = require("codewars.api.utils")

    describe("handle_res auth detection", function()
        it("detects 401 as auth error", function()
            local _, err = api_utils.handle_res({ exit = 0, status = 401, body = '{"error":"Unauthorized"}' })
            assert.is_not_nil(err)
            assert.truthy(err.auth)
            assert.truthy(err.msg:find("Session expired"))
        end)

        it("detects 403 as auth error", function()
            local _, err = api_utils.handle_res({ exit = 0, status = 403, body = "Forbidden" })
            assert.is_not_nil(err)
            assert.truthy(err.auth)
        end)

        it("does not flag 404 as auth error", function()
            local _, err = api_utils.handle_res({ exit = 0, status = 404, body = '{"reason":"Not found"}' })
            assert.is_not_nil(err)
            assert.is_nil(err.auth)
            assert.are.equal(404, err.status)
        end)

        it("does not flag 500 as auth error", function()
            local _, err = api_utils.handle_res({ exit = 0, status = 500, body = "Internal Server Error" })
            assert.is_not_nil(err)
            assert.is_nil(err.auth)
            assert.are.equal(500, err.status)
        end)

        it("returns nil error on success", function()
            local res, err = api_utils.handle_res({ exit = 0, status = 200, body = '{"ok":true}' })
            assert.is_nil(err)
            assert.is_not_nil(res)
            assert.truthy(res.ok)
        end)
    end)
end)
