describe("Cookie.parse", function()
    local Cookie = require("codewars.cache.cookie")

    it("parses valid cookie string", function()
        local cookie, err = Cookie.parse("CSRF-TOKEN=abc123; _session_id=xyz789;")
        assert.is_nil(err)
        assert.is_not_nil(cookie)
        assert.are.equal("abc123", cookie.csrf_token)
        assert.are.equal("xyz789", cookie.session_id)
    end)

    it("parses without trailing semicolons", function()
        local cookie, err = Cookie.parse("CSRF-TOKEN=abc123; _session_id=xyz789")
        assert.is_nil(err)
        assert.are.equal("abc123", cookie.csrf_token)
        assert.are.equal("xyz789", cookie.session_id)
    end)

    it("returns error for missing CSRF-TOKEN", function()
        local cookie, err = Cookie.parse("_session_id=xyz789;")
        assert.is_nil(cookie)
        assert.is_not_nil(err)
        assert.truthy(err:find("CSRF"))
    end)

    it("returns error for missing _session_id", function()
        local cookie, err = Cookie.parse("CSRF-TOKEN=abc123;")
        assert.is_nil(cookie)
        assert.is_not_nil(err)
        assert.truthy(err:find("session_id"))
    end)

    it("handles case-insensitive CSRF (csrf-token)", function()
        local cookie, err = Cookie.parse("csrf-token=abc123; _session_id=xyz789;")
        assert.is_nil(err)
        assert.are.equal("abc123", cookie.csrf_token)
    end)

    it("returns error for empty string", function()
        local cookie, err = Cookie.parse("")
        assert.is_nil(cookie)
        assert.is_not_nil(err)
    end)

    it("handles URL-encoded CSRF token values", function()
        local cookie, err = Cookie.parse("CSRF-TOKEN=abc%3D123; _session_id=xyz789;")
        assert.is_nil(err)
        assert.are.equal("abc%3D123", cookie.csrf_token)
    end)

    it("preserves original string", function()
        local str = "CSRF-TOKEN=abc123; _session_id=xyz789;"
        local cookie = Cookie.parse(str)
        assert.are.equal(str, cookie.str)
    end)
end)
